import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";


import Link from "next/link";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" />
           <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300..700;1,300..700&family=Indie+Flower&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="navbar navbar-expand-lg ">
  <div className="container-fluid">
    <a className="navbar-brand" href="#">School Hub</a>
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div className="navbar-nav mx-auto">
        <Link className="nav-link " href="/">Home</Link>
         <Link className="nav-link" href="/about">About</Link>
        <Link className="nav-link" href="/services">Services</Link>
        <Link className="nav-link" href="/contact">Contact</Link>
      </div>
    </div>
  </div>
</nav>
        {children}
        <footer className="footer mt-5 pt-5">
  <div className="container">
    <div className="row gy-4">

      <div className="col-lg-4 col-md-6">
        <h4 className="footer-brand">School Hub</h4>
        <p className="footer-text">
          A smart platform connecting schools, parents, and students
          in one modern digital experience.
        </p>
      </div>

     
      <div className="col-lg-2 col-md-6">
        <h6 className="footer-title mb-3 ms-2">Platform</h6>
        <ul className="footer-links">
          <li><Link href="/">Home</Link></li>
          <li><Link href="/about">About</Link></li>
          <li><Link href="/services">Services</Link></li>
          <li><Link href="/contact">Contact</Link></li>
        </ul>
      </div>

      <div className="col-lg-3 col-md-6 ">
        <h6 className="footer-title mb-3 ms-3">Support</h6>
        <ul className="footer-links">
          <li><a href="#">Help Center</a></li>
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms & Conditions</a></li>
        </ul>
      </div>

      <div className="col-lg-3 col-md-6">
        <h6 className="footer-title mb-3">Contact</h6>
        <p className="footer-text-email mb-1"> support@schoolhub.com</p>
        <p className="footer-text"> Jordan</p>
      </div>

    </div>


    <div className="text-center footer-bottom">
      © {new Date().getFullYear()} School Hub. All rights reserved.
    </div>
  </div>
</footer>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
  
}
